copyright: 2023 The ChatKC Team
site_name: ChatKC Docs
site_url: https://chatkc.github.io
site_description: ChatKC Docs
repo_url: https://github.com/chatkc/chatkc.github.io
repo_name: ChatKC Docs

nav:
    - Home: index.md
    - Protocol: protocol.md
    - Clients: clients.md
    - Bridges: bridges.md

theme:
  logo: images/chatkccircle.png
  favicon: images/chatkcsquarelowres.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.expand
    - navigation.sections
    - navigation.path
    - navigation.footer
    - navigation.indexes

  font:
    text: Inconsolata
  name: material
extra_css:
  - stylesheets/extra.css
extra:
 analytics:
    provider: google
    property: G-1XP6QJ5VKZ
 generator: false
